# Generated by Django 2.2.3 on 2019-07-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField()),
                ('desc', models.TextField(verbose_name='分类描述')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('pub_date', models.DateTimeField(verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
    ]
