# Generated by Django 2.2.3 on 2019-07-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
