# Generated by Django 2.2.3 on 2019-07-29 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190725_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='文章标签', max_length=20, verbose_name='文章标签')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '标签管理',
                'verbose_name_plural': '标签管理',
                'ordering': ['-tag'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=68, verbose_name='文章标题')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='文章描述')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_related', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_related', to='blog.Category', verbose_name='分类')),
                ('tags', models.ManyToManyField(to='blog.Tags', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
    ]
